### ISSUE TITLE
[To-Do]: 1.13 Road Map

### ISSUE THREAD

**Issue by Lanse505** [Coders-After-Dark/Reskillable#130]
# Major
- [ ] Move the Config over to the new TOML format
- [ ] Split Config Locks into JSON 
	- [Possibly Consider TOML - Ask SkySom for Info]
- [ ] Split Skill/Trait Configs into JSON 
	- [Possibly Consider TOML - Ask SkySom for Info]
- [ ] Move PlayerSkillInfo from NBT/Packets to Capabilities

# Medium
- [ ] Look into implementing -  https://github.com/Coders-After-Dark/Reskillable/issues/42 - After the Split of Locks to JSONs are done.
- [ ] GUI Improvements/Rework for the Skill-Info Screen

# Minor
- [ ] Overall Code Clean-Up
- [ ] Look into making Skill/Trait and Lock JSON's Reloadable
- [x] Implement Customizable Chorus Transmutation
- [ ] Implement "Re-Skill" Points
	- Allows for the "Un-Selection" of Traits.
	- Acquired by Villager Trading
	- Acquired by Random Loot in Churches
